# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Graphentechnologien in den digitalen Geisteswissenschaften
email: andreas.kuczera@adwmainz.de
description: > # this means to ignore newlines until "baseurl:"
  Modellierung – Import – Exploration. 
  Entstanden an der Digitalen Akademie der Akademie der Wissenschaften und der Literatur, Mainz.
baseurl: "/Graphentechnologien" # the subpath of your site, e.g. /blog
url: "http://kuczera.github.io" # the base hostname & protocol for your site
twitter_username: andreaskuczera
github_username: kuczera

# Build settings
markdown: kramdown
kramdown:
  parse_block_html: true
